### ISSUE TITLE
joblib.my_exceptions.JoblibTypeError: JoblibTypeError

### ISSUE THREAD

**Issue by SeekPoint** [benedekrozemberczki/diff2vec#1]
mldl@ub1604:~/ub16_prj/diff2vec$ python src/diffusion_2_vec.py
lapack_opt_info:
    libraries = ['openblas']
    library_dirs = ['/usr/local/lib']
    language = f77
blas_opt_info:
    libraries = ['openblas']
    library_dirs = ['/usr/local/lib']
    language = f77
openblas_info:
    libraries = ['openblas']
    library_dirs = ['/usr/local/lib']
    language = f77
openblas_lapack_info:
    libraries = ['openblas']
    library_dirs = ['/usr/local/lib']
    language = f77
blas_mkl_info:
  NOT AVAILABLE

---------------------------
Feature extraction starts.
---------------------------

  0%|                                                                                                                                                                                 | 0/10 [00:00<?, ?it/s]Traceback (most recent call last):
  File "src/diffusion_2_vec.py", line 60, in <module>
    main(args)
  File "src/diffusion_2_vec.py", line 54, in main
    walks = run_parallel_feature_creation(args.input,  args.vertex_set_cardinality, args.num_diffusions, args.workers)
  File "src/diffusion_2_vec.py", line 35, in run_parallel_feature_creation
    results = Parallel(n_jobs = num_of_workers)(delayed(create_features)(i, edge_list_path, vertex_set_cardinality) for i in tqdm(range(number_of_replicates)))
  File "/usr/local/lib/python2.7/dist-packages/joblib/parallel.py", line 789, in __call__
    self.retrieve()
  File "/usr/local/lib/python2.7/dist-packages/joblib/parallel.py", line 740, in retrieve
    raise exception
joblib.my_exceptions.JoblibTypeError: JoblibTypeError

**Comment by benedekrozemberczki** [comment]
Are your package versions in line with the package versions listed?

**Comment by SeekPoint** [comment]
yes, pretty sure

**Comment by SeekPoint** [comment]
mldl@ub1604:~/ub16_prj/diff2vec$ git diff
diff --git a/src/diffusiontrees.py b/src/diffusiontrees.py
index 7eab72a..1be6b83 100644
--- a/src/diffusiontrees.py
+++ b/src/diffusiontrees.py
@@ -36,9 +36,9 @@ class EulerianDiffuser:
                 sub_graph.add_edges_from([(end_point, sample), (sample, end_point)])
                 if infected_counter == self.number_of_nodes:
                     break
-        euler = [str(u) for u,v in nx.eulerian_circuit(sub_graph, start_node)]
+        euler = [str(u) for u,v in nx.eulerian_circuit(sub_graph, node)]
         if len(euler) == 0:
-            euler = [str(u) for u,v in nx.eulerian_circuit(graph, start_node)]
+            euler = [str(u) for u,v in nx.eulerian_circuit(graph, node)]
         return euler
 
     def run_diffusions(self):
mldl@ub1604:~/ub16_prj/diff2vec$
